### ISSUE TITLE
unable to build for non-std targets

### ISSUE THREAD

**Issue by osimmac** [ua-kxie/pid-ctrl#2]
get errors about not being able to compile num-traits for all sorts of reasons. in the cargo.toml of pid-ctrl, this must be added:
`[dependencies.num-traits]`
`version = "0.2.15"`
`default-features = false`
`# features = ["libm"]    # <--- Uncomment if you wish to use 'Float' and 'Real' without std`

by doing that, it seems to build fine

**Comment by Iraeis** [comment]
I see you've already fixed this issue in a fork. Did you want to sync your fork back upstream?

**Comment by osimmac** [comment]
Sure! that'd be cool. I'll make a pr: #3

**Comment by Iraeis** [comment]
merged. I also found and removed references to num-traits float (instead of floatcore)

If you could kindly confirm on your end that the issue is fixed and close the issue.

**Comment by Iraeis** [comment]
closing without confirmation
